apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace:
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
       - name: tomcat
         image: dockertejdeep123/dockerimage:ovaledgee4 
         env:
          - name: OVALEDGE_MYSQL_URL
            value: "jdbc:mysql://database-1.c560uxygxrjh.ap-south-1.rds.amazonaws.com:3306/ovaledgedb?useSSL=false"
          - name: OVALEDGE_MYSQL_USER
            value: "admin"
          - name: OVALEDGE_MYSQL_PWORD
            value: "ovaledge123"
          - name: OVALEDGE_ENCRYPT_DECRYPT_KEY
            value: "ovaledge2021"
          - name: OVALEDGE_SAML_META_DATA
            value: "https://ovaledge-ma.okta.com/app/exkbqnqdbnfYdOJEe5d6/sso/saml/metadata"
          - name: OVALEDGE_SECURITY_TYPE
            value: "db"
          - name: SAML_METADATA_TYPE
            value: "url"
          - name: ENTITY_BASE_PROTOCOL
            value: "https"
          - name: ENTITY_BASE_HOST
            value: "fg.ovaledge.net"
          - name: ext.properties.dir
            value: "/usr/local/tomcat/conf/"
          - name: ENTITY_BASE_CONTEXTPATH
            value: "/ovaledge"
          - name: ENTITY_BASE_PORT
            value: "443"
          - name: ENTITY_BASE_PORT_INURL
            value: "false"
          - name: ENTITY_BASE_ISLB
            value: "false"
          - name: entityBaseURL
            value: ""
         ports:
         - containerPort: 9090

